version: 2
jobs:
  build:
    working_directory: ~/HTTParty
    docker:
    - image: circleci/ruby:2.6-rc-node
      environment:
        BUNDLE_JOBS: 3
        BUNDLE_RETRY: 3
        BUNDLE_PATH: vendor/bundle
        PGHOST: 127.0.0.1
        PGUSER: circleci-demo-ruby
        RAILS_ENV: test
    steps:
    - checkout
    - run:
        name: Which bundler?
        command: bundle -v
    - restore_cache:
        keys:
        - rails-demo-bundle-v2-{{ checksum "Gemfile.lock" }}
        - rails-demo-bundle-v2-
    - run:
        name: Bundle Install
        command: bundle check || bundle install
    - save_cache:
        key: rails-demo-bundle-v2-{{ checksum "Gemfile.lock" }}
        paths:
        - vendor/bundle
    - run:
        name: Run Cucumber
        command: |
          bundle exec cucumber --format pretty --format html --out=test_results/features_report.html
    - store_test_results:
        path: ~/HTTParty/test_results
    - store_artifacts:
        path: ~/HTTParty/test_results
    environment:
    - CIRCLE_COMPARE_URL: https://github.com/Joao-gui/httparty_novo/compare/1bc41eda6f120165d6c878dc281c8b5b88675e86...0524318eb6894496ea89f0b5fc70fcaae52999e0
workflows:
  version: 2
  all_commits:
    jobs:
    - build:
        filters:
          branches:
            ignore:
            - developer
            - test